### ISSUE TITLE
Switch default branch to main

### ISSUE THREAD

**Issue by inktomi** [rock3r/deep-clean#11]
It seems like many projects have adopted `main` as the default branch, and it's the default for new repos here on github  (and it's more inclusive language). Would you be willing to change the default branch here as well? It's always a bit of context switch for me when I go to check for updates to this project - I have muscle memory around `git pull origin main` (and `fish` autocompletes that for me) so it's a tiny bit jarring to back up and type `master`.

**Comment by rock3r** [comment]
Hi there! As you may have noticed, this script doesn't get many updates (mostly cause it doesn't need them). As such, for as much as I understand the use case, it's not really something that needs checking more than once or twice a year.

On top of that, I'm quite reticent to changing the main branch name when I have no other significant changes to make. When the script will require changes next, I will consider it again 🤗

**Comment by inktomi** [comment]
That makes sense. Thank you!
