### ISSUE TITLE
Incompatible with kscript 4

### ISSUE THREAD

**Issue by rock3r** [rock3r/deep-clean#12]
The script doesn't work with kscript 4. Need to update it to make it work, as there were some breaking changes in the kscript major release. See https://github.com/holgerbrandl/kscript/blob/master/NEWS.md#402

**Comment by marcorighini** [comment]
@rock3r do you have an eta for this to be fixed? Thanks!

**Comment by rock3r** [comment]
@marcorighini just checked and it seems to be working fine, at least on macOS. I pushed some minor cleanup, try with the newer script?

**Comment by francescocervone** [comment]
@rock3r tried on macOS with kscript 4.1.1 and it doesn't work. Only works with kscript 3.1.0.
Here is a log of the error
```bash
➜  deep-clean --help
[kscript] Resolving com.offbytwo:docopt:0.6.0.20150202...
[kscript] [ERROR] Compilation of scriplet failed:
[kscript] [ERROR] Command     : 'bash -c /opt/homebrew/Cellar/kotlin/1.7.10/libexec/bin/kotlinc  -classpath '/Users/francescocervone/.m2/repository/com/offbytwo/docopt/0.6.0.20150202/docopt-0.6.0.20150202.jar' -d '/Users/francescocervone/.cache/kscript/jar_4ad675cd9c7bcedd2d43ea018efbe55d/scriplet.jar' '/Users/francescocervone/.cache/kscript/jar_4ad675cd9c7bcedd2d43ea018efbe55d/Deep_clean.kts' '/Users/francescocervone/.cache/kscript/jar_4ad675cd9c7bcedd2d43ea018efbe55d/Main_Deep_clean.kt''
[kscript] [ERROR] Exit Code   : 1
[kscript] [ERROR] Stdout      : ''
[kscript] [ERROR] Stderr      : '/Users/francescocervone/.cache/kscript/jar_4ad675cd9c7bcedd2d43ea018efbe55d/Deep_clean.kts:3:8: error: unresolved reference: Deep_clean[nl]import Deep_clean.CommandLineArguments[nl]       ^[nl]'
[kscript] [ERROR]
```

**Comment by rock3r** [comment]
I did work on it on macOS, kscript 4.1.1. You didn't update the script, that import doesn't exist anymore :)

**Comment by rock3r** [comment]
Wait no wtf I removed it... but it's still there. Maybe the IDE added it back automatically 🙄  I'll check again as soon as I can.

**Comment by rock3r** [comment]
Ok, had time (finally! sorry it took so long) and can confirm it indeed works fine with KScript 4 after removing the import. While I was at it, I also added a small check to make sure the Gradle wrapper is available and show a nice error if not, instead of crashing.
