### ISSUE TITLE
missing dependency error 

### ISSUE THREAD

**Issue by letroll** [rock3r/deep-clean#3]
**Describe the bug**
Hello, 

first, thank you for your kscript.
I'm working on Windows 7 and have kotlinc, kscript and mvn working. 
I use Msys2 terminal and when I want use your script I have the following error:

```
deep-clean.kts:3:7: error: unresolved reference: DependsOn
@file:DependsOn("com.offbytwo:docopt:0.6.0.20150202")                                          │@file:DependsOn("com.offbytwo:docopt:0.6.0.20150202")
```
.
**System information**
 - OS version: Windows 7
 - Kotlin version: 1.2.50
 - Maven version:  3.3.9
 - KScript version:  2.4.4
 - Script version: last (from git master)

**Comment by rock3r** [comment]
Thanks!

It's an odd issue; I'm not doing anything weird there, nor there's anything Windows-specific at that point of the code. Maybe it's worth opening an issue on [KScript](https://github.com/holgerbrandl/kscript) and see if they have any better idea of what's going on?

**Comment by rock3r** [comment]
Closing due to a month of inactivity
